config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    member do
      get 'assign_job'
      post 'create_job'
      get 'add_video'
      post 'upload_video'
      get 'edit_job/:job_id', action: 'edit_job'
      post 'update_job/:job_id', action: 'update_job'
      delete 'destroy_job/:job_id', action: 'destroy_job'
      get 'show_video/:video_id', action: 'show_video'
      delete 'delete_video/:video_id', action: 'delete_video'
      post 'update_video/:video_id', action: 'update_video'
    end
  end
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'movies#index'
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :assign_job, :create_job, :edit_job, :update_job, :destroy_job, :add_video, :upload_video, :show_video, :delete_video, :update_video]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @people = Person.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @people = Person.all
    @videos = @movie.videos.all
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  def assign_job
    @people = Person.all
  end

  def edit_job
    @job = Job.find(params[:job_id])
    @person = Person.find(@job.person_id)
  end

  def add_video
  end

  def show_video
    @video = Video.find(params[:video_id])
  end

  def update_video
    @video = Video.find(params[:video_id])
    @video.properties = params[:video][:properties].to_unsafe_h

    respond_to do |format|
      if @video.save     
        format.html { redirect_to @movie, notice: 'Video properties were successfully updated.' }
        format.json { render :show_video, status: :ok, location: @movie }
      else
        format.html { render :show_video }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def upload_video
    @movie.videos.create(movie_params[:videos])
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Video was successfully uploaded.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :add_video }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_job
    @job = Job.find(params[:job_id])
    @movie.update_position(@job.id, movie_params[:job][:position])
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Job was successfully edited.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :edit_job }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_job
    @movie.add_position(movie_params[:person][:person_id], movie_params[:person][:jobs][:position])
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Job was successfully assigned.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :assign_job }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end



  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { render :show, status: :ok, location: @movie }
    end
  end

  def destroy_job
    Job.find(params[:job_id]).destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_video
    Video.find(params[:video_id]).destroy
    respond_to do |format|
      format.html { redirect_to @movie, notice: 'Video was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :job_id, :video_id, person: [:person_id, jobs: [:position]], job: [:position, :id], videos: [:video_file]) 
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def assign_job_path(id)
    "/movies/#{id}/assign_job"
  end

  def edit_job_path(id, job_id)
    "/movies/#{id}/edit_job/#{job_id}"
  end

  def destroy_job_path(id, job_id)
    "/movies/#{id}/destroy_job/#{job_id}"
  end

  def add_video_path(id)
    "/movies/#{id}/add_video"
  end

  def show_video_path(id, video_id)
    "/movies/#{id}/show_video/#{video_id}"
  end
  
  def delete_video_path(id, video_id)
    "/movies/#{id}/delete_video/#{video_id}"
  end

  def update_video_path(id, video_id)
    "/movies/#{id}/update_video/#{video_id}"
  end
end

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/add_video.html.erb
<%= form_for @movie, url: {action: 'upload_video'}, method: :post do |m_form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this job from being assigned:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1><%= @movie.title %></h1>
  <div class="field">
    <table>
      <tr>
        <%= m_form.fields_for :videos do |v_field| %>
        <td><%= v_field.file_field :video_file %></td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= m_form.submit %>
  </div>
<% end %>

app/views/movies/assign_job.html.erb
<%= form_for @movie, url: {action: 'create_job'}, method: :post do |m_form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this job from being assigned:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1><%= @movie.title %></h1>
  <div class="field">
    <strong>Select People</strong><br>
    <%= m_form.fields_for :person do |p_field| %>
      <table>
      <tr>
        <td><%= p_field.label :list_of_people %></td>
        <td><%= p_field.collection_select :person_id, Person.all, :id, :name, prompt: true %></td>
        <%= p_field.fields_for :jobs do |j_field| %>
        <td><%= j_field.text_field :position %></td>
        <% end %>
      </tr>
      </table>
    <% end %>
  </div>
  <div class="actions">
    <%= m_form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Assign a new job', assign_job_path(@movie.id) %> | 
<%= link_to 'Movie Main Page', movies_path %>

app/views/movies/edit_job.html.erb
<%= form_for @movie, url: {action: 'update_job'}, method: :post do |m_form| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this job from being assigned:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1><%= @movie.title %></h1>
  <div class="field">
    <table>
      <tr>
        <td><%= @person.name %></td>
        <%= m_form.fields_for @job do |j_field| %>
        <td><%= j_field.text_field :position %></td>
        <% end %>
      </tr>
    </table>
  </div>
  <div class="actions">
    <%= m_form.submit %>
  </div>
<% end %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Movie Main Page', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @movie.title %><br>
  <strong>Team:</strong>
  <table>
    <% @movie.jobs.each do |job| %>
      <tr>
        <td><%= link_to job.person.name, job.person %></td>
        <td><%= job.position %></td>
        <td><%= link_to 'Edit Job', edit_job_path(@movie.id, job.id) %></td>
        <td><%= link_to 'Destroy', destroy_job_path(@movie.id, job.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</p>
<p>
  <strong>Videos:</strong>
  <table>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to "#{video.video_file_file_name}", show_video_path(@movie.id, video.id) %></td>
        <td><%= link_to 'Download', video.video_file.url(:original, false) %></td>
        <td><%= link_to 'Delete', delete_video_path(@movie.id, video.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Assign Jobs', assign_job_path(@movie.id) %> | 
<%= link_to 'Add a Video', add_video_path(@movie.id) %> |
<%= link_to 'Movie Main Page', movies_path %>

app/views/movies/show_video.html.erb
<%= form_for @video, url: {action: 'update_video', controller: 'movies'}, method: :post do |v_form| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being updated:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <h1><%= @video.video_file_file_name %></h1>
    <table>
      <tr>
        <td>Movie:</td><td><%= @movie.title %></td>
      </tr><tr>
        <td>Video size:</td><td><%= number_to_human_size(@video.video_file_file_size) %></td>
      </tr><%= fields_for :properties do |p_field| %><tr>
          <td>Resolution:</td><td><%= p_field.text_field :resolution, value: @video.properties[:resolution] %></td>
      </tr><tr>
        <td>Container:</td><td><%= p_field.text_field :container, value: @video.properties[:container] %></td>
      </tr><% end %>
    </table>
  </div>
  <div class="actions">
    <%= v_form.submit %>
  </div>
<% end %>